#!/usr/bin/env bash
# (we use env for non-Linux OSes)
#
# Wrapper script for Lisp invocation with quicklisp preloaded.
# Based on code from clbuild by Luke Gorrie and contributors.

###
### Initialize $base variable
###
### This code can't be factored out into internal/ because we need $base
### set before we can find internal/
###

# exit on any error
set -e

# MacOS doesn't have "readlink -e", needed to follow symlinks.
# We hack it using readlink, dirname, and cd.
readlink_e() {
    self="$0"
    while test -h "$self"; do
	cd "$(dirname $self)"
	self=`readlink "$self"`
    done
    cd "$(dirname $self)"
    pwd
}
base=$(readlink_e)
internal=$base/internal


###
### Load configuration files
###
source "$base/qlbuild.conf.default"
if test -f "$base/qlbuild.conf"; then
    source "$base/qlbuild.conf"
fi


###
### Load sources
###
source $internal/util.sh
source $internal/ql.sh
source $internal/slime.sh
source $internal/impl.sh

###
### Choose a Lisp
###

if test "$1" = "--implementation" ; then
    $LISP_IMPLEMENTATION_TYPE=$2
    shift 2
fi
configure_implementation

###
### Main commands
###

source $internal/main.sh
